#!/usr/bin/env bash

branch_name="conflict-feature"
file_name="feature.js"

git branch -D "$branch_name"
git checkout -b "$branch_name"
touch "$file_name"
echo "function newFeature() {}" > "$file_name"
git add .
git commit -am "New feature works"
git checkout -
touch "$file_name"
echo "function oldFeatureFixes() {}" > "$file_name"
git add .
git commit -am 'Old feature fix'
